### ISSUE TITLE
hud disabled my mastercomfig config

### ISSUE THREAD

**Issue by greginsomtimrem** [jakadak/ahud-cc#2]
what else can i say

**Comment by jakadak** [comment]
I also use mastercomfig and it works for me, mhmmmm

Which version/extensions are you using?

**Comment by greginsomtimrem** [comment]
im using latest version

**Comment by rwaij** [comment]
Was confused why mastercomfig wasn't working on a fresh TF2 install, this issue seems to be the case for me. Using the latest version of both mastercomfig (9.10.3) and ahud-cc (16th august). With the ahud-cc-master folder removed comfig loads up as shown with the ASCII art on console and the settings changing, with ahud-cc installed (dropped ahud-cc-master directly in customs) the ASCII art disappears, though some of the changed settings stay. 

Also some of the modules like removed explosions, flat mouse and null-cancelling movement are still enabled with ahud-cc installed, but I don't think the main comfig preset works, I checked settings in-game with after changing my comfig preset to High from Low and my textures were still at Low. Only after removing ahud-cc does it change.

**Comment by jakadak** [comment]
Thank you, so i added support for Master Config (and removed my preloading config:)
https://github.com/jakadak/ahud-cc/commit/ca74751fee67d0b14b38faea61235fd096c8ac15

**Comment by rwaij** [comment]
thank you so much for the continued work! I love this hud :)
